NAMSAN-MT/Namsan

package.json, src/components/common/List/List.style.ts, src/components/common/List/List.tsx, src/components/common/List/List.type.ts, src/components/common/List/index.tsx, src/styles/GlobalStyles.ts, src/styles/mixin.style.ts, src/styles/varialbes.style.ts, yarn.lock
- feature/List
- List 컴포넌트 추가
- 각 카테고리, 상세카테고리별 코드 수정 필요 (현재 임시로 넣어놓은 상태)
- 임시로 만든 페이지 (PR에는 포함되어있지않습니다.)
=> 리스트 컴포넌트 추가

src/components/common/GNB/GNB.style.ts, src/components/common/GNB/GNB.tsx, src/components/common/Input/Input.interface.ts, src/components/main/FifthSection/FifthSection.tsx, src/components/main/ThirdSection/ThirdSection.tsx, src/pages/index.tsx
변경사항
- DEV_SSR 설정을 통해 확인되는 Hydration 오류 수정
- 추정원인: browser 환경에서만 지연로딩함으로 서버환경과 브라우저 환경이 불일치 됨에 의해 오류 발생함으로 추정
- waring 발생중인 GNB 내부 styledComponent 속성을 `transient prop`로 표기
- <img width="553" alt="image" src="https://user-images.githubusercontent.com/49890780/227779651-e34f6f2d-c6ce-42d8-ad4f-1ebb9d15d01d.png">
- 추정원인: 같은 환경의 다른 컴포넌트는 이상이 없을을 볼때, gatsby 자체적으로 제공하는 `Link` 태그를 기반으로 만든것이 원인일 것으로 추정. 
TODO
- (개발환경) DEV_SSR 설정 켠 후 일부 페이지에서 Failed to Server Render (SSR) 발생.  원인 파악 및 해결 필요 (최초시작시, 업무분야 페이지, 업무분야 상세 페이지, 구성원 상세페이지에서 발생중)
- 
- <img width="576" alt="image" src="https://user-images.githubusercontent.com/49890780/227779212-55ebeac4-ad4a-44a9-923d-258e89d411b9.png">
- (배포환경) 일부 페이지에서   `Minified React error` 발생중. 원인 파악 및 해결 필요 (업무분야 상세 페이지, 구성원 상세페이지에서 발생중)
=> [fix]: SSR 오류 수정

.firebaserc, firebase.json, functions/.eslintrc.js, functions/.gitignore, functions/package-lock.json, functions/package.json, functions/src/index.ts, functions/tsconfig.dev.json, functions/tsconfig.json
feature/setting-algolia
- [google functions algolia 셋팅] (https://console.firebase.google.com/u/0/project/namsan-801de/functions?hl=ko)
- google cloud 로그 탐색기(모니터링) 셋팅
- 현재 aloglia 기준으로 셋팅한 인덱스 기준으로 이용 및 배포시 에러 메세지 로그 적재
- [로그 탐색기](https://console.cloud.google.com/logs/query;query=severity%3DERROR;cursorTimestamp=2023-04-02T14:33:56.868283787Z?authuser=0&project=namsan-801de)
- 현재 알고리아에는 더미 데이터 400개가 쌓여있는 상태(무시)
- 현재 google functions 활성화한 상태로 `news` collection 기준으로 데이터 작업 예정(테스트 전단계)
- [Alogolia Docs](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/how-to/importing-with-the-api/?utm_medium=page_link&utm_source=dashboard&client=javascript)
- 현재 `news` 데이터는 firestore에 저장되지 않고 [Algolia Index인 `dev_namsan`](https://www.algolia.com/apps/Y8N8F5MBXZ/explorer/b …
=> google functions + algolia CRUD 작성

src/components/common/List/List.tsx
변경사항
- 업무분야 list 버튼 onClick location 로직 수정
=> fix: href 수정

.gitignore, gatsby-config.ts, gatsby-node.ts, gatsby-ssr.tsx, package.json, src/api/index.api.ts, src/api/member.api.ts, src/components/common/GNB/GNB.tsx, src/components/contact/ContactSection/ContactSection.tsx, src/components/contact/Divider/Divider.style.ts, src/components/contact/RecruiteSection/RecruiteSection.style.ts, src/components/member/Member/Member.interface.ts, src/components/member/Member/Member.tsx, src/components/members/SelectBox/SelectBox.style.ts, src/interface/api.interface.ts, src/intl/ko.json, src/pages/member/[id].tsx, src/pages/work/[id].tsx, yarn.lock
- feature/amend
- SSR환경에서 하이드레이팅 에러 수정 
- contact UI 깨짐 수정
- contact 페이지 지도 마커 달기
=> [FEAT] SSR 하이드레이팅 문제 수정 + 컨택트페이지 지도 API 마커추가

src/components/news/Card/Card.interface.ts, src/components/news/Card/Card.style.ts, src/components/news/Card/Card.tsx, src/components/news/Main/Main.style.ts, src/components/news/Main/Main.tsx, src/components/news/Main/useMain.hook.ts, src/components/news/Pagination/Pagination.helper.ts, src/components/news/Pagination/Pagination.interface.ts, src/components/news/Pagination/Pagination.tsx
- fix/pagination+complete+lazy
- `Pagination` 요구사항에 맞춰 로직 완성
- `Card` 컴포넌트 lazy loading 
-  Main, Card, Pagination 세부 파일 분리 작업
=> 페이지네이션 작업완료 + Card 컴포넌트 lazy loading

src/api/member.api.ts, src/components/members/MemberList/MemberList.tsx, src/components/members/SearchBar/SearchBar.hook.ts, src/components/members/SearchBar/SearchBar.interface.ts, src/components/members/SearchBar/SearchBar.tsx, src/pages/members.tsx
- fix/members-search-api
- 멤버페이지 버그 수정
=> [FIX] 검색 카테고리 API대신 graphql 값으로 불러오도록 수정

src/pages/news.tsx
=> [fix] news 메인 페이지 serverData 제거

src/components/news/Main/Main.tsx, src/components/news/NewsWrapper/NewsWrapper.style.ts
=> [FIX] 폰트 패밀리 적용

src/components/news/Main/Main.tsx, src/components/news/NewsDetail/NewsDetail.tsx, src/intl/ko.json, src/pages/news/[id].tsx
- fix/news-detail-csr
- 소식 상세정보 SSR -> CSR 변경
=> [FIX] 소식 상세 정보 CSR 호출 변경

src/pages/member/[order].tsx
* develop -> master  (#83)
* [FIX] 소식 > Tab 이동 이슈  수정 (#76)
* [FIX] 소식 상세 정보 CSR 호출 변경 (#78)
* [FIX] 뉴스 상세 GraphQL 적용 (#80)
* [hotfix] member페이지 빌드에러 수정
---------
=> members 빌드에러 hotfix (#103)

functions/src/index.ts, gatsby-node.ts, src/api/algolia.ts, src/api/index.api.ts, src/api/news.api.ts, src/components/news/NewsDetail/NewsDetail.interface.ts, src/components/news/NewsDetail/NewsDetail.style.ts, src/components/news/NewsDetail/NewsDetail.tsx, src/interface/api.interface.ts
* NewDetila 영역 order 값 추가
* order + profile api 조회
* 프로필 이미지 반응형 스타일 적용
* 이미지 조회 api 수정
* 이전/다음글 이동 기능 추가
* NewDetila 영역 order 값 추가
* order + profile api 조회
* 프로필 이미지 반응형 스타일 적용
* 이미지 조회 api 수정
* 이전/다음글 이동 기능 추가
* 이미지 올리기
* gatsby 이미지
* image
* 뉴스 상세 상단 이미지 graphQL 적용
* 알골리아 order 조건 맞춰서 조회
* 알골리아 order 조건 google-functions 적용
=> 뉴스 상세 이미지(GraphQL 호출) + 알골리아 order 조건 조회 적용(with.google-functions (#110)

package.json, src/components/common/GNB/GNB.style.ts, src/components/main/Banner/Banner.style.ts, src/components/main/FifthSection/FifthSection.style.ts, src/components/main/FirstSection/FirstSection.hook.ts, src/components/main/FirstSection/FirstSection.style.ts, src/components/main/FirstSection/FirstSection.tsx, src/components/main/ForthSection/ForthSection.style.ts, src/components/main/ThirdSection/ThirdSection.style.ts, src/styles/GlobalStyles.ts, yarn.lock
- fix/main-page
- 디자인 검수 + 메인 인트로 수정
=> [FIX] 디자인 검수 + 메인 인트로 수정

src/components/introduce/IntroduceWrapper/IntroduceWrapper.style.ts, src/components/member/IntroduceItem/IntroduceItem.style.ts, src/components/member/Member/Member.style.ts, src/components/members/MemberList/MemberList.style.ts, src/components/members/SearchBar/SearchBar.style.ts
- fix/sumin-design
- 소개/구성원 페이지 디자인 검수 일부 반영
=> [FIX] 디자인 검수 일부 반영 (소개/구성원 페이지)

src/components/news/NewsDetail/NewsDetail.style.ts, src/components/news/NewsDetail/NewsDetail.tsx, src/intl/en.json
=> 소식 상세 아이콘 이슈 수정

src/components/news/NewsDetail/NewsDetail.style.ts
=> 소식 상세 프로필 스타일 수정

src/components/common/Footer/Footer.style.ts, src/components/common/GNB/GNB.style.ts, src/components/common/GNB/GNB.tsx, src/components/icons/LogoIcon/LogoIcon.tsx, src/components/main/Banner/Banner.style.ts, src/components/main/FifthSection/FifthSection.style.ts, src/components/main/FirstSection/FirstSection.style.ts, src/components/main/ForthSection/ForthSection.style.ts, src/components/main/ThirdSection/ThirdSection.style.ts
- fix/main-page
- 20230530 디자인 검수 수정
=> [FIX] 20230530 디자인 검수 수정

src/intl/ko.json
=> [FIX] 띄어쓰기 제거

src/components/common/GNB/GNB.style.ts, src/components/common/GNB/GNB.tsx, src/components/main/FirstSection/FirstSection.hook.ts, src/components/main/FirstSection/FirstSection.style.ts, src/components/main/FirstSection/FirstSection.tsx
- fix/main-page
- GNB 애니메이션 변경
=> [FIX] HOTFIX 수정

src/components/common/GNB/GNB.style.ts, src/components/common/GNB/GNB.tsx, src/components/common/Layout/Layout.hook.ts, src/components/common/Layout/Layout.interface.ts, src/components/common/Layout/Layout.tsx, src/components/common/LottieWrapper/LottieWrapper.interface.ts, src/components/common/LottieWrapper/LottieWrapper.tsx, src/components/main/FirstSection/FirstSection.style.ts
- fix/main-page
-  gnb 포커스 할 때 텍스트 이동 현상 수정
-  메인 텍스트 폰트 깨짐
- 플로팅 버튼 (맨 위로 가기 버튼) 애니메이션 수정]
=> [FIX] 검수 수정

src/components/contact/ContactSection/ContactSection.style.ts, src/components/contact/ContactSection/ContactSection.tsx, src/components/contact/RecruiteSection/RecruiteSection.tsx, src/intl/en.json, src/intl/ko.json, src/styles/varialbes.style.ts
* [FIX] 띄어쓰기 제거
* [fix] 법무법인 디자인검수 적용
---------
=> Fix/namsan corp (#162)

src/components/member/Member/Member.tsx, src/components/work/work.styled.ts
=> [FIX] 업무분야 디자인 수정 반영

src/components/main/Banner/Banner.style.ts
- fix/pages
-  메인 20230605 디자인 반영 수정
=> [FIX] 메인 20230605 디자인 반영 수정

src/components/member/Member/Member.tsx, src/components/work/DetailPage.tsx, src/pages/work/[id].tsx
=> fix: 빌드오류 수정

src/components/main/Banner/Banner.style.ts
=> [FIX] 배너 모바일 사이즈 변경

gatsby-node.ts, src/components/member/Member/Member.tsx
* [FIX] 변호사 배경이미지 없는 경우 추가
* [FIX] 변호사 태그 클릭 안되는 이슈 수정
---------
=> [FIX] 변호사 태그 클릭 안되는 이슈 수정  (#189)

src/components/main/Banner/Banner.tsx, src/components/main/FifthSection/FifthSection.hook.ts
- fix/pages
- [FIX] 스타일 및 버그 수정(회사소개서, 인재모집)
=> [FIX] 스타일 및 버그 수정(회사소개서, 인재모집)

src/api/news.api.ts, src/components/news/Main/Main.hook.ts, src/components/news/Main/Main.style.ts, src/components/news/NewsDetail/NewsDetail.style.ts
- fix/news-design-fix-20230606
- 디자인 검수사항 적용
- 검색 순서 오류 수정
- 탭 이동 이슈 수정
=> [FIX] 뉴스 디자인 검수 사항 적용

src/components/main/Banner/Banner.style.ts
=> [FIX] 배너 모바일 스타일 수정

src/components/common/GNB/GNB.tsx
- feat/mobile-menu-en
- [FIX] 모바일메뉴에서 영문화 페이지로 이동하지 않는 문제 수정
=> [FIX] 모바일메뉴에서 영문화 페이지로 이동하지 않는 문제 수정

src/components/common/GNB/GNB.tsx, src/pages/news.tsx
=> [FIX] GNB 에러 해결

src/api/news.api.ts, src/components/news/NewsDetail/NewsDetail.style.ts, src/components/news/NewsDetail/NewsDetail.tsx, src/interface/api.interface.ts
- feat/news/authors
-[FIX] 뉴스 작성자 다수 조회할 수 있도록 수정
=> [FIX] 뉴스 작성자 다수 조회할 수 있도록 수정
